version: '3'
services:
  ischool-backend-gateway:
    container_name: ischool-backend-gateway
    build:
      context: ./iSchool-gateway
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - mynetwork

  ischool-user-service:
    container_name: ischool-user-service
    build:
      context: ./iSchool-service/iSchool-user
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - mynetwork
    depends_on:
      - ischool-backend-gateway

  ischool-search-service:
    container_name: ischool-search-service
    build:
      context: ./iSchool-service/ischool-search
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
      - "9005:9005"  # 执行器端口
    networks:
      - mynetwork
    depends_on:
      - ischool-user-service

  ischool-community-service:
    container_name: ischool-community-service
    build:
      context: ./iSchool-service/ischool-community
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    networks:
      - mynetwork
    depends_on:
      - ischool-user-service
      - ischool-backend-gateway

  xxl-job:
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: ischool-xxl-job
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=xxx
      - SERVER_PORT=9000
      - XXL_JOB_ACCESS_TOKEN=xxx




  ischool-python-service:
    container_name: ischool-python-service
    build:
      context: ../iSchool-Python-Service
      dockerfile: Dockerfile
    ports:
      - "10086:10086"
    networks:
      - mynetwork

  # 前端服务
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"                    # 如果nginx需要代理多个端口，在后面加-就可以，yml的列表语法
    volumes:
      - "../nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/html:/usr/share/nginx/html"
    depends_on:
      - ischool-backend-gateway
    networks:
      - mynetwork


networks:
  mynetwork:
