version: '3'
services:
  mysql:
    image: mysql:8.0.30
    container_name: ischool-mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxx
    ports:
      - "3306:3306"
    volumes:
      - ../data/.mysql-data:/var/lib/mysql
      - ../data/mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - mynetwork

  redis:
    image: redis:5.0.14
    container_name: ischool-redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/.redis-data:/data
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.13.2-management
    container_name: ischool-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: xxx
      RABBITMQ_DEFAULT_PASS: xxx
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../data/.rabbitmq-data:/var/lib/rabbitmq
    networks:
      - mynetwork

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: ischool-nacos
    ports:
      - "8848:8848"
      - "9848:9848"  # 添加这一行来映射 gRPC 端口
      - "9849:9849"
    volumes:
      - ../data/.nacos-data:/home/nacos/data
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - NACOS_AUTH_ENABLE=false
    networks:
      - mynetwork

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: ischool-elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=xxx
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - ../data/.elasticsearch-data:/usr/share/elasticsearch/data
      - ../data/.analysis:/usr/share/elasticsearch/plugins
    networks:
      - mynetwork


networks:
  mynetwork:
